apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ fio_name }}  # FIO workload name
  namespace: {{ namespace }}  # OpenShift namespace
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: {{ fio_name }}
  template:
    metadata:
      labels:
        app: {{ fio_name }}
    spec:
      containers:
        - name: fio
          securityContext:
            runAsUser: 0
            privileged: true
          image: quay.io/ocsci/nginx:fio
          command:
            - fio
          args:
            - "--name={{ fio_name }}"
            - "--rw=randwrite"
            - "--size=4G"
            - "--bs=4k"
            - "--numjobs=4"
            - "--runtime=60"
            - "--group_reporting"
            - "--time_based"
            - "--filename=/dev/blockdevice"  # Block device path
          volumeDevices:  # Using volumeDevices for Block mode
            - name: fio-volume
              devicePath: /dev/blockdevice  # Path to block device inside the container
      restartPolicy: Always
      volumes:
        - name: fio-volume
          persistentVolumeClaim:
            claimName: {{ pvc_claim_name }}  # PVC claim name for block device
  strategy:
    type: Recreate